import { apiRequest } from './axiosInstance'; import { unwrapApiResponse } from './apiResponse'; import type { ApiResponse, PageResponse } from '@/types/api'; import type { Project, ProjectChecklistItem } from '@/types/backendContractor'
export async function createProject(data: { quoteId: number; constructionItems: string }) { return unwrapApiResponse<Project>(await apiRequest<ApiResponse<Project>>({ method: 'POST', url: '/api/projects', data, authenticated: true }), '프로젝트 생성에 실패했습니다.') }
export async function getContractorProjects() { return unwrapApiResponse<PageResponse<Project>>(await apiRequest<ApiResponse<PageResponse<Project>>>({ method: 'GET', url: '/api/projects/contractor/me', authenticated: true }), '프로젝트 목록 조회에 실패했습니다.') }
export async function getLandlordProjects() { return unwrapApiResponse<Project[]>(await apiRequest<ApiResponse<Project[]>>({ method: 'GET', url: '/api/projects/landlord/me', authenticated: true }), '프로젝트 목록 조회에 실패했습니다.') }
export async function getProject(id: number) { return unwrapApiResponse<Project>(await apiRequest<ApiResponse<Project>>({ method: 'GET', url: `/api/projects/${id}`, authenticated: true }), '프로젝트 조회에 실패했습니다.') }
export async function startProject(id: number) { return unwrapApiResponse<Project>(await apiRequest<ApiResponse<Project>>({ method: 'POST', url: `/api/projects/${id}/start`, authenticated: true }), '착공 처리에 실패했습니다.') }
export async function requestProjectCompletion(id: number) { return unwrapApiResponse<Project>(await apiRequest<ApiResponse<Project>>({ method: 'POST', url: `/api/projects/${id}/request-completion`, authenticated: true }), '완료 요청에 실패했습니다.') }
export async function confirmProjectCompletion(id: number) { return unwrapApiResponse<Project>(await apiRequest<ApiResponse<Project>>({ method: 'POST', url: `/api/projects/${id}/confirm-completion`, authenticated: true }), '완료 확인에 실패했습니다.') }
export async function updateProjectSchedule(id: number, data: { startDate: string; completionDate: string; reason: string }) { return unwrapApiResponse<Record<string, unknown>>(await apiRequest<ApiResponse<Record<string, unknown>>>({ method: 'PATCH', url: `/api/projects/${id}/schedule`, data, authenticated: true }), '일정 변경에 실패했습니다.') }
export async function addProjectChecklistItem(id: number, label: string) { return unwrapApiResponse<ProjectChecklistItem>(await apiRequest<ApiResponse<ProjectChecklistItem>>({ method: 'POST', url: `/api/projects/${id}/checklist`, data: { label }, authenticated: true }), '체크리스트 추가에 실패했습니다.') }
export async function updateProjectChecklistItem(id: number, itemId: number, completed: boolean) { return unwrapApiResponse<ProjectChecklistItem>(await apiRequest<ApiResponse<ProjectChecklistItem>>({ method: 'PATCH', url: `/api/projects/${id}/checklist/${itemId}`, data: { completed }, authenticated: true }), '체크리스트 변경에 실패했습니다.') }
